name:                distributed-key-value
version:             0.1.0.0
github:              "githubuser/distributed-key-value"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/githubuser/distributed-key-value#readme>

dependencies:
  - base >= 4.7 && < 5
  - distributed-process
  - distributed-process-simplelocalnet
  - distributed-static
  - containers
  - binary
  - stm
  - async
  - template-haskell
  - network

library:
  source-dirs: src

executables:
  db:
    main:                db.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - distributed-key-value

tests:
  distributed-key-value-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - distributed-key-value
